### ISSUE TITLE
Fritzing file?

### ISSUE THREAD

**Issue by erichiggins** [sparkfun/MAX3232_Breakout#1]
Is there a Fritzing file available for this breakout board? I'm not seeing it within the Fritzing parts library.

**Comment by bboyho** [comment]
Hi!

Hmm, looking at our [Fritzing parts repository](https://github.com/sparkfun/Fritzing_Parts/tree/main/products), I don't believe we have made one for that specific part yet. This seems like a simple part, I might have some time to make the part within the next month.

I'll have to place the design files through the Eagle-to-Fritzing converter and see what happens.

**Comment by erichiggins** [comment]
Thank you!

**Comment by bboyho** [comment]
The Eagle-to-Fritzing converter did some funky things but I managed to debug the issues (multiple instances of a few Eagle libraries in the XML file...). Enjoy!

https://github.com/sparkfun/Fritzing_Parts/blob/main/products/11189-sfe_transceiver_breakout_max3232_rs232_converter_ttl.fzpz
